def imageName = 'flask-app'
def dockerFilePath = 'DAY-07'
def imageTobePush = 'abdulmusavvirrohe/srechallenge-flaskapp'
pipeline{
    agent any
    stages{
        stage('code checkout'){
            steps{
                checkout scm
            }
        }
        stage('unit test'){
            steps{
                sh "docker build -t ${imageName}:${env.BUILD_ID} -f ${WORKSPACE}/${dockerFilePath}/Dockerfile ."
                sh "docker run --rm ${imageName} pytest"
            }
        }
        stage('image tagging'){
            steps{
                sh "docker tag ${imageName}:${env.BUILD_ID} ${imageTobePush}:${env.BUILD_ID}"
            }
        }
        stage('Image Push'){
            steps{
                withDockerRegistry(credentialsId: '12f766c2-ffca-4c23-a162-f5ca1b89142a', url: 'abdulmusavvirrohe/srechallenge') {
                    sh "docker push ${imageTobePush}:${env.BUILD_ID}"
                }
            }
        }
    }
    post{
        success{
            echo 'Docker image built, tested, tagged and pushed successfully'
        }
        failure{
            echo 'Pipeline failed'
        }
    }

}
